application: talk-here
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  mime_type: text/plain
  expiration: 10000d

- url: /
  script: main.app

- url: /static
  static_dir: static
