application: talk-here
version: 3 
runtime: python27
api_version: 1 
threadsafe: yes

inbound_services:
  - channel_presence

handlers:

# favicon
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  mime_type: text/plain
  expiration: 10000d

# robots
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
  expiration: 10000d

# cache css,js,img
- url: /css
  mime_type: text/css
  expiration: 10000d
  static_dir: static/css
- url: /img
  expiration: 10000d
  static_dir: static/img
- url: /js
  static_dir: static/js
  expiration: 10000d

# catch all for static files
- url: /static
  static_dir: static

# catch all other requests
- url: .*
  script: main.app

# custom error handlers
#error_handlers:
#- file: templates/server_error.html
#- error_code: xx
#  file: xx
#- error_code :xx
#  file: xx

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/git/.*
- ^(.*/)?.*/svn/.*
- ^(.*/)?\..*
- ^(.*/)?README$
- ^(.*/)?.*\.bak$
